//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSiteBanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatHang
    {
        public DatHang()
        {
            this.ChiTietDatHang = new HashSet<ChiTietDatHang>();
        }
    
        public int MaDH { get; set; }
        public Nullable<int> MaKH { get; set; }
        public Nullable<System.DateTime> NgayDat { get; set; }
        public Nullable<System.DateTime> NgayGiao { get; set; }
        public Nullable<bool> TinhTrangGiao { get; set; }
        public Nullable<bool> DaThanhToan { get; set; }
        public Nullable<int> UuDai { get; set; }
    
        public virtual ICollection<ChiTietDatHang> ChiTietDatHang { get; set; }
        public virtual KhachHang KhachHang { get; set; }
    }
}
