//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSiteBanHang.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    public partial class ThanhVien
    {
        public ThanhVien()
        {
            this.BinhLuan = new HashSet<BinhLuan>();
            this.KhachHang = new HashSet<KhachHang>();
        }
        [DisplayName("Mã thành viên")]
        public int MaTV { get; set; }
        [DisplayName("Tên tài khoản")]
        [StringLength(20,ErrorMessage="{0} không được quá 20 ký tự")]
        [Required(ErrorMessage="{0} không được bỏ trống")]
        public string TaiKhoan { get; set; }
        [DisplayName("Mật khẩu")]
        public string MatKhau { get; set; }
        public string HoTen { get; set; }
        public string DiaChi { get; set; }
        public string Email { get; set; }
        public string SoDienThoai { get; set; }
        public string CauHoi { get; set; }
        public string CauTraLoi { get; set; }
        public Nullable<int> MaLTV { get; set; }
    
        public virtual ICollection<BinhLuan> BinhLuan { get; set; }
        public virtual ICollection<KhachHang> KhachHang { get; set; }
        public virtual LoaiThanhVien LoaiThanhVien { get; set; }
    }
}
